name: CI Deploy

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  IMG: ghcr.io/kokuwaio/iot-mock

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Publish to Registry
        uses: jerray/publish-docker-action@master
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_ACTION_TOKEN }}
          registry: ghcr.io
          repository: kokuwaio/iot-mock
          auto_tag: true